### ISSUE TITLE
Problem with vector gfx

### ISSUE THREAD

**Issue by amastm** [Jonathan-LeRoux/IguanaTex#1]
Hi ~,

![2017-07-14 10_56_00-iguanatex](https://user-images.githubusercontent.com/7069797/28205621-12b672e0-6883-11e7-86bc-d20b2fd7be2a.png)
I get the VB error "this member can be only accessed for a group" using the vectorized formulas.
Enable all macros is turned on (no security).

Best,
Andre

**Comment by Jonathan-LeRoux** [comment]
Hi Andre,
I just tried the same setting as you (DVI + Vector) and it works fine on my end.
A few things that come to mind:
- Does everything work okay with Bitmap? 
-What happens if you use pdflatex as LaTeX engine?
- Are you able to use TeX2Img outside PowerPoint?
- Try running with "Debug" checked.
- Are you using a non English version of PowerPoint? Can you post a screenshot of PowerPoint's selection pane after trying to create the display on an empty slide?
If none of this works, we'll have to go into debug mode in VBA.
Best,
Jonathan

**Comment by amastm** [comment]
It works with Windows 7, PPT 2010, but on Windows 7 x64 and PPT 2013 this problem occurs.
He stops here:
![image](https://user-images.githubusercontent.com/7069797/28261526-f3deaf54-6adf-11e7-849c-ad2173d8aab0.png)

**Comment by Jonathan-LeRoux** [comment]
How does the selection pane evolve when you go through the steps starting at `Set Shr = inSh.Ungroup`?
Can you try the following two things:
- insert the generated .emf file (the one in the Temp folder) using IguanaTex's "Insert vector graphics file". I assume you'll get the same error, but let's see.
-  insert that same .emf file via the Insert feature of Powerpoint, then Ungroup it twice: what do you get in the selection pane?
Can you send me the .emf file?

**Comment by Jonathan-LeRoux** [comment]
Vector graphics sometimes leads to errors such as the one reported here, but in my experience, these are not easily reproducible, and often get away when generating a new display with the same content. 
Closing for now, please reopen if needed.
