### ISSUE TITLE
alt text feature request

### ISSUE THREAD

**Issue by monroews** [Jonathan-LeRoux/IguanaTex#11]
For ADA compliance it would be great if there were a way to add alt text that would be available with the picture of the equation. With the current system if I add alt text in powerpoint, then if I regenerate the equation the alt text is deleted. So it would be awesome if there were a way to include the alt text in the LaTeX editor. 

This is part of a larger effort to make our PowerPoint slides ADA compliant for online teaching.

Thanks for amazing software!

**Comment by Jonathan-LeRoux** [comment]
Thanks for the suggestion. I can look into this, but I'd like to know more about the desired outcome.
I think it is feasible to programmatically set an alt text to a display in Powerpoint, but we need to decide what to put in it. 
The easiest thing I see is to simply put the full LaTeX text in the alt text. 
A slightly more involved option would be to only include what is inside the `\begin{document}...\end{document}`.
Yet another option would be not to try to put anything in the alt text automatically, but to keep whatever is in there. Or to put the LaTeX content when creating a new display, but keep whatever is in there when editing.
I would be inclined to think that the simplest option is also the best, because it's the only one that guarantees the alt text actually matches the content of the display, even if it's not very readable.
What do you think would be the most useful for ADA compliance?

**Comment by monroews** [comment]
I'm trying to get more guidance on what is needed for ADA compliance and I'll post that as soon as I get it. It appears that MathML might be a good option for the alt text. I agree that simple is better and an ideal solution would be the LaTeX code.

I like the idea of putting the LaTeX text in the alt text.
That alt text should be updated to match any edits to the equation.
This option would also make it easy for anyone to copy the LaTeX equation even if they don't have IguanaTex and that would be handy for my students.

It isn't clear to me if you'd be able to know if the content of the alt text was originally created by IguanaTex or by the user. If you can't tell, then I'd always update the alt text to match the equation.

**Comment by Jonathan-LeRoux** [comment]
It would be great if you could look into alternative options for the alt text. I agree tat the only reasonable way forward is something that gets automatically created from the LaTeX source, every time, to make sure it's consistent with the content. Maybe converting to MathML could help with that, but I'm thinking that it is very likely to break very often, whenever a user creates a table, a complicated graph, etc.
So my inclination would be to put whole LaTeX source in the alt text. That would have the added benefit, as you mention, that people without IguanaTex may be able to retrieve the underlying source.

**Comment by Jonathan-LeRoux** [comment]
The implementation of the simple version we mentioned is really trivial.
Just adding the following lines at [Line 777 of LatexForm.frm](https://github.com/Jonathan-LeRoux/IguanaTex/blob/a12959ba7db7fa4c53a42a650f7a1952c22712b5/LatexForm.frm#L777):
```  newShape.AlternativeText = TextBox1.Text
    If UseEMF = True Then
        newShape.Title = "IguanaTex Vector Display"
    Else
        newShape.Title = "IguanaTex Bitmap Display"
    End If
```
Here is the .pptm file, please git it a try (unzip, open, "save as" a .ppam, then load the add-in): [IguanaTex_v1_58.zip](https://github.com/Jonathan-LeRoux/IguanaTex/files/4720755/IguanaTex_v1_58.zip)

**Comment by monroews** [comment]
Hi Jonathan,

Thanks for the amazingly quick release of this new version! This works just
as expected. I think it would be cleaner to strip the LaTeX down to the
code that is between the $$. You wouldn't want to have to listen to a
screen reader go through all of the preamble.

I have not received any clear guidance from the team at Cornell that is
working on ADA compliance and so I'm not ready to go regenerate all of my
equations just yet. I'll send an email to that team showing what you have
done and see if I get any feedback.

Best regards,

Monroe Weber-Shirk | Senior Lecturer | he/him

Phone: +1 (607) 216-8445  | mw24@cornell.edu  | Zoom
<https://cornell.zoom.us/j/6658208237?pwd=cWxvK0p4eloyS1F3d3lLcG1ia0dyUT09>



AguaClara Cornell | Safe Water on Tap

Cornell University | 303 Hollister Hall | Ithaca, NY 14853 |
AguaClara.cornell.edu <http://aguaclara.cee.cornell.edu/>

<http://aguaclara.cornell.edu/>

**Comment by Jonathan-LeRoux** [comment]
Hi Monroe,

I'm a bit ambivalent about including the preamble or not. I agree that the screen reader won't be great with all the preambles, but it won't be great even without it, so I thought we might just put the whole source code so that at least people who don't have IguanaTex can take it and compile the code. I guess I could make that an option, although that would require a bit more work.

Thanks,
Jonathan

**Comment by monroews** [comment]
Jonathan,

I'd wait for now because it isn't yet clear to me what is actually required
for ADA compliance. This is a real issue that has a lot of people worried
right now as universities move to online instruction. It seems unlikely
that LaTeX will be enough to meet compliance. I'll let you know if I hear
anything definite.

Monroe Weber-Shirk | Senior Lecturer | he/him

Phone: +1 (607) 216-8445  | mw24@cornell.edu  | Zoom
<https://cornell.zoom.us/j/6658208237?pwd=cWxvK0p4eloyS1F3d3lLcG1ia0dyUT09>



AguaClara Cornell | Safe Water on Tap

Cornell University | 303 Hollister Hall | Ithaca, NY 14853 |
AguaClara.cornell.edu <http://aguaclara.cee.cornell.edu/>

<http://aguaclara.cornell.edu/>

**Comment by Jonathan-LeRoux** [comment]
Got it, I'll put this on the back burner for now.
Best,
Jonathan

**Comment by Jonathan-LeRoux** [comment]
Alt text now includes the LaTeX source since v1.58. I don't think there's a better alternative for ADA compliance that can be realistically implemented.
