### ISSUE TITLE
Could not start process on latest PP and Texlive in latest MS Win10

### ISSUE THREAD

**Issue by lobpcg** [Jonathan-LeRoux/IguanaTex#16]
I get Could not start process and no image embedded, although the debug shows no errors and I can see the correct image actually being  generated in the working directory. I run the latest PP and Texlive.

**Comment by Jonathan-LeRoux** [comment]
Hi Andrew,

Is this on a new installation of IguanaTex? If so, rebooting the laptop sometimes help.
If not, which version of IguanaTex are you using?
What happens if you run with the debug box checked?

Thanks,
Jonathan

**Comment by lobpcg** [comment]
New installation of the latest stable IguanaTex I have performed a month ago. It never worked. The debug info is normal as expected from latex output. And the image file is being generated correctly despite of the error message, just doesn't get embedded into ppt. Should I try the latest beta?

I also have a very similar installation elsewhere but with an older Texlive, which works fine on the same ppt file.

**Comment by Jonathan-LeRoux** [comment]
You could try the latest beta, but I'm curious first to know exactly what happens when you check "debug" at the bottom left of the IguanaTex window before clicking "Generate". This should pause at each step of the process and show you which command is going to be run. That will tell you which command failed, and it will copy that command in your clipboard, so that you could open a CMD window, navigate to your Temp folder, and paste that command to see its output.
My guess is that there is a problem with ghostscript or imagemagick, potentially a path that is not set correctly.

**Comment by Jonathan-LeRoux** [comment]
Your issue may be related to this recently reported one: https://github.com/Jonathan-LeRoux/IguanaTex/issues/15#issuecomment-821219529
Please check that %USERPROFILE% has been replaced by the full path with your username in the Main Settings window (for example, click on the "..." button on the side to confirm the file path, and that should correctly set the path).
Note that the latest beta version does automatically replace it upon saving the settings, so that would also solve the issue, but just replacing should do the trick.

**Comment by lobpcg** [comment]
Jonathan, yes, thanks for your advice, the paths were wrong apart from latex, so the dvi conversion could not be completed. 
Debug messages were not helpful to realize this. 

Your  http://www.jonathanleroux.org/software/iguanatex/faq.html :
Q: When pressing the Generate button in IguanaTex, I get the error message: Could not start process: 'latex -interaction=batchmode "addin_tmp.tex"'. GetLastError returned 0.
A: This problem occurs when IguanaTex is unable to locate LaTeX in order to compile your Latex file.

appears incomplete, since exactly the same error message came in my case, where Latex was fine, but further conversion from dvi was broken due to incorrect paths. May be try reproducing my situation by putting wrong paths and improve the error messages and the documentation to be more helpful?

Anyway, I now have the dvi conversion from latex using both bitmap and vector working, so the issue can be closed.  

Thanks for your great effort to keep this excellent tool open sourced and updated! 

Best, Andrew

**Comment by Jonathan-LeRoux** [comment]
I'm surprised you would get the exact same error with `'latex -interaction=batchmode "addin_tmp.tex"'`, because that error really means that IguanaTex could not start the latex process.
Which path did you have to change / was wrong?

**Comment by lobpcg** [comment]
All my paths were wrong: GS,  IM, and T2I.

You raise a good point, I am unsure if my error has been exactly the same word-by-word. It just looked the same. Since the error massage text unfortunately cannot be copy/pasted, I have not reproduced it in this issue.

**Comment by Jonathan-LeRoux** [comment]
Thanks for confirming, Andrew, I see what happened now.
The latest beta version uses a different error form. Currently, the error message itself cannot be copied, but I'll think about adding that.
