### ISSUE TITLE
Bug: Endless loop of warnings if editing picture that was not created by IguanaTex

### ISSUE THREAD

**Issue by klieret** [Jonathan-LeRoux/IguanaTex#30]
Steps:

1. Paste any bitmap to PowerPoint
2. Select
3. `Edit LaTeX display`

An error like this gets displayed (as it should):

<img width="478" alt="image" src="https://user-images.githubusercontent.com/13602468/169689955-1cad91a0-4bff-4ae6-97ee-fb0dd7b17675.png">

However, every time I click it away, it appears again. The only solution seems to be to force quite PowerPoint.

This is on Mac Silicon with

*    IguanaTex 1.59
*    gs 9.56.1
*    ppt 16.60

**Comment by Jonathan-LeRoux** [comment]
This was reported in https://github.com/Jonathan-LeRoux/IguanaTex/issues/24, and should no longer occur in v1.60 (released yesterday), could you please give it a try?

**Comment by Jonathan-LeRoux** [comment]
To be clear, I don't know why one would get stuck in an endless loop there. What I did do in v1.60 is change the default path for the LaTeXiT extractor to a sandbox folder where we can check for the existence of the extractor without triggering a request for permission to access the folder by Mac OS. When the path to the extractor (in Main Settings) starts with that default folder, then we check for its existence and only try the extraction if it exists.
So, someone who has another path stored in the settings (which may be the case when upgrading from an older version) may still get this issue, because IguanaTex won't check if the extractor exists.
In any case, the workaround is to set the path to the extractor in Main Settings to `/Library/Application Support/Microsoft/Office365/User Content.localized/Add-Ins.localized/`.
For those who do want to use the LaTeXiT extractor, please make sure to set its permissions correctly:
`chmod 755 ./LaTeXiT-metadata-macos`
`sudo cp ./LaTeXiT-metadata-macos '/Library/Application Support/Microsoft/Office365/User Content.localized/Add-Ins.localized/'`
