### ISSUE TITLE
BUG: Could not start process when open a file in OneDrive directory

### ISSUE THREAD

**Issue by BreakVoid** [Jonathan-LeRoux/IguanaTex#34]
When I am editing a file in OneDrive directory, "Insert vector graphics file" does not work well.
![image](https://user-images.githubusercontent.com/8384350/183286694-cec6e9cf-ff0b-458e-bbb8-edc51f9f73ae.png)

After I copied the file out of OneDrive directory, it works well.

**Comment by aoconnor-ufl** [comment]
Try making that OneDrive folder available offline and see if that helps.

**Comment by Jonathan-LeRoux** [comment]
Thanks for reporting this, I can reproduce this issue on my end.

This is due to the fact that the function to insert vector graphics uses the presentation folder as default location to launch a process, whereas other functions to create/edit displays use the Temp folder, and the Windows API function CreateProcessA does not seem to like being called with a OneDrive directory as the current directory. I'm not sure if that is a bug on the Windows API side or not, but anyhow, the directory in which we launch the process doesn't matter, as I (ironically) write [in the comments](https://github.com/Jonathan-LeRoux/IguanaTex/blob/24b673d97475e0574a1e9f2e5b4b9cfbff4da303/LoadVectorGraphicsForm.frm#L131): "The StartFolder doesn't really matter here because everything is relative to the input file, we just need any folder from which to launch the commands". Well, it turns out it does matter here!

The easy fix is to comment out the `If ActivePresentation.path <> vbNullString` clause:
```
    'If ActivePresentation.path <> vbNullString Then
    '    StartFolder = ActivePresentation.path
    'Else
    If GetTempPath() <> vbNullString Then
        StartFolder = GetTempPath()
    Else
        #If Mac Then
            StartFolder = "/"
        #Else
            StartFolder = "C:\"
        #End If
    End If
```
Here is an updated version of the .pptm with the fix: [IguanaTex_v1_60_2.zip](https://github.com/Jonathan-LeRoux/IguanaTex/files/9277706/IguanaTex_v1_60_2.zip)
Please let me know if this work on your end.

**Comment by BreakVoid** [comment]
> Thanks for reporting this, I can reproduce this issue on my end.
> 
> This is due to the fact that the function to insert vector graphics uses the presentation folder as default location to launch a process, whereas other functions to create/edit displays use the Temp folder, and the Windows API function CreateProcessA does not seem to like being called with a OneDrive directory as the current directory. I'm not sure if that is a bug on the Windows API side or not, but anyhow, the directory in which we launch the process doesn't matter, as I (ironically) write [in the comments](https://github.com/Jonathan-LeRoux/IguanaTex/blob/24b673d97475e0574a1e9f2e5b4b9cfbff4da303/LoadVectorGraphicsForm.frm#L131): "The StartFolder doesn't really matter here because everything is relative to the input file, we just need any folder from which to launch the commands". Well, it turns out it does matter here!
> 
> The easy fix is to comment out the `If ActivePresentation.path <> vbNullString` clause:
> 
> ```
>     'If ActivePresentation.path <> vbNullString Then
>     '    StartFolder = ActivePresentation.path
>     'Else
>     If GetTempPath() <> vbNullString Then
>         StartFolder = GetTempPath()
>     Else
>         #If Mac Then
>             StartFolder = "/"
>         #Else
>             StartFolder = "C:\"
>         #End If
>     End If
> ```
> 
> Here is an updated version of the .pptm with the fix: [IguanaTex_v1_60_2.zip](https://github.com/Jonathan-LeRoux/IguanaTex/files/9277706/IguanaTex_v1_60_2.zip) Please let me know if this work on your end.

I downloaded the file and tried the pptm file by copying the file to OneDrive directory. The function works well.  Thanks a lot.

**Comment by Jonathan-LeRoux** [comment]
Thanks for confirming! v1.60.2 release closes this issue.
