### ISSUE TITLE
Input text bug (on Mac)

### ISSUE THREAD

**Issue by Atcold** [Jonathan-LeRoux/IguanaTex#40]
When trying to move the plugin GUI using [Spectacle](https://github.com/eczarny/spectacle), only the text input is moved. 

<img width="1531" alt="Screenshot 2022-10-13 at 15 00 43" src="https://user-images.githubusercontent.com/2119355/195931077-a0dc0dc4-627c-417a-bcd7-b30d0fce7f14.png">

I think there's some bug related to the text input. The content is different (there's an additional `\usepackage{amsmath}` in the dark editor).

**Comment by tsung-ju** [comment]
I did a quick testing, and it seems that windows created using the add-in API simply doesn't support being moved by apps like Spectacle or Rectangle.app, so we have to wait for Microsoft to fix this.

The latex input is actually implemented as a separate native window (which can be moved by Spectacle), hence the inconsistency.

**Comment by Atcold** [comment]
I'm confused about the fact that there are 2 input windows.
Do you know what's going on there?

**Comment by tsung-ju** [comment]
Yes, that part was written by me. The main reason I added a separate window is because the textbox control provided by the add-in api (of macOS PowerPoint) lacks many editing features (such as copy/paste/undo etc). So I added an overlay window (which contains only a single textbox) using native macOS apis. Since the textbox is native, it supports most editing features. The overlay window is positioned right above the original textbox, so normally users won't notice there are 2 textboxes.
In your screenshot, the white textbox is the original one, and the black textbox is the native one. The add-in only uses latex code from the black textbox. The latex code inside white textbox is just some placeholder text that's no longer used.

**Comment by Atcold** [comment]
> the textbox control provided by the add-in api (of macOS PowerPoint) lacks many editing features (such as copy/paste/undo etc)

That's insane 😳😳😳

So… shall I close this issue since it seems unfixable?

**Comment by tsung-ju** [comment]
I think so. Actually it might be possible to avoid using a separate window for text, but even so we still have to wait for MS to make the add-in window movable by other apps.

**Comment by Atcold** [comment]
Closing because the bug is @microsoft's.

**Comment by Jonathan-LeRoux** [comment]
Note that Microsoft isn't likely to do anything unless they're made aware of the bug. Best way is to send feedback via the Help menu in PowerPoint. And it can't hurt to ask a question in [Microsoft Community](https://answers.microsoft.com/en-us) and get the attention of an MVP there.
