### ISSUE TITLE
Bitmap is not bitmap (on Mac)

### ISSUE THREAD

**Issue by Atcold** [Jonathan-LeRoux/IguanaTex#41]
Opening this issue following the discussion on #39 about the "bitmap" option generating "vectorial" graphics on Mac.

Suggested fix: let the user choose between SVG, PDF, and PNG.
If PDF is not available (on Windows), then disable it in the menu.

**Comment by Jonathan-LeRoux** [comment]
Sorry for letting this open so long.

I think the real difference between all these formats is how PowerPoint handles the objects, and that's basically either as "Picture" or as "Shape". This changes how the user can interact with them, so I think it's still important to keep them separate. Plus, having PDF under "Picture" and SVG under "Shape" allows the user to use the trick you mentioned to obtain a good aspect ratio in SVG, i.e., first generate as PDF, then convert to SVG.

I'm thus thinking of implementing this as follows:
- Replace "Rasterize selection" with "Convert to Picture", and "Vectorize selection" with "Convert to Shape". I'm a bit sad of losing the word "selection", but I'm hoping it's clear enough (in particular that this can be applied to multiple objects, a whole slide, or sets of slides).
- On Mac, the user will be able to choose between PDF and PNG in a new "Create Picture output as" menu under Main Settings, and between SVG via DVI or SVG via PDF (no change) under a renamed "Create Shape output as" menu. 
- On Windows, there will be no change except for renaming "Create Vector output as" to "Create Shape output as" (no new "Create Picture output as" menu because only option is PNG).

Does that sound reasonable?

**Comment by Jonathan-LeRoux** [comment]
I tried both with and without "selection" and the version with it doesn't look as clean:
![convert_to_menu](https://github.com/Jonathan-LeRoux/IguanaTex/assets/14299374/3336e9a2-ebc5-4da6-884b-fa07814378d2)
![convert_selection_to_menu](https://github.com/Jonathan-LeRoux/IguanaTex/assets/14299374/0cb9b078-173e-4590-af90-231caec8e80b)

Thanks a lot for popularizing IguanaTex! I admit that a YouTube video tutorial is something I should have done a long time ago, but never got to do (and probably don't have the necessary talent for...). So if you could do one, that would be fantastic!
Apart from the obvious ones, some of the probably lesser known/used features are the batch edit under "Regenerate selection", the templates in the edit window, and the keyboard shortcuts ("accelerators"). There's also the fact that one can add some of the macros to the Quick Access Toolbar, but unfortunately [that only works on Windows due to a Microsoft bug](https://github.com/Jonathan-LeRoux/IguanaTex/issues/23) (I haven't checked recently but they hadn't fixed it a couple months ago).

**Comment by Atcold** [comment]
Maybe, let's create a draft over the Christmas break?
How shall we coordinate?

**Comment by Jonathan-LeRoux** [comment]
I spoke too fast. `dvipng` can't process the XDV files that `xelatex` outputs and chokes on fonts in the DVI files that `lualatex` outputs. This only leaves `pdflatex` for which we could force DVI output, but that is literally what "latex (DVI)" is. To avoid confusion, I'll just raise an error saying "ImageMagick is required with all engines except latex (DVI) for PNG output". At least the code won't break anymore if no ImageMagick path is specified.

**Comment by Jonathan-LeRoux** [comment]
Here is a [beta version of v1.61](https://github.com/Jonathan-LeRoux/IguanaTex/files/13554586/IguanaTex_v1_61_beta1.zip), which includes the following changes:
- (Win/Mac) Changed Bitmap/Vector naming to Picture/Shape, to reflect the actual difference in how PowerPoint handles each type of display. The naming also better suits the fact that Picture displays on Mac are PDF and thus cannot be described as Bitmap. (Fixes https://github.com/Jonathan-LeRoux/IguanaTex/issues/41)
- (Win/Mac) Raise an error if user tries to use a combination of engine and output which requires ImageMagick without its path pointing to a file that exists (i.e., PNG output with all engines other than "latex (DVI)").
- (Mac) Implemented PNG support for Mac
- (Win/Mac) Fixed bug that could occur when using dvipng and there exists already a PNG file from a prior run.

**Comment by Jonathan-LeRoux** [comment]
Closing this issue as it is now fixed in [Release v1.61](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.61).
