### ISSUE TITLE
The fraction bar disappears when I regenerate it.

### ISSUE THREAD

**Issue by winkelmesser123** [Jonathan-LeRoux/IguanaTex#45]
When I regenerate the equation that includes the \frac command, the fraction bar disappears.
And I wonder why the margin between the numerator and the fraction bar is so wide.
I used v1.60.2.

![image](https://user-images.githubusercontent.com/77262212/209425449-eb16df13-b38d-4d73-85b5-9843453195ed.png)

**Comment by Jonathan-LeRoux** [comment]
My guess is that you are generating a vector display using "SVG via PDF w/ dvisvgm". This leads to issues for some displays because PDFs handle straight lines differently from curved lines. You can see more details about this in [this closed issue](https://github.com/Jonathan-LeRoux/IguanaTex/issues/22#issuecomment-972287547).
The recommended solution is to use "SVG via DVI w/ dvisvgm". Please let me know if that works for you.

**Comment by winkelmesser123** [comment]
Thank you very much for your useful information!
The problems were solved by using "EMF w/ pdfiumdraw" and I was able to obtain appropriate output images without any problems.

**Comment by Jonathan-LeRoux** [comment]
Note that "EMF w/ pdfiumdraw" does often result in slightly distorted displays. I would recommend using "SVG via DVI w/ dvisvgm", which should be the most reliable.
