### ISSUE TITLE
Run-time error "5"  Invalid procedure call or argument

### ISSUE THREAD

**Issue by nmgzjf** [Jonathan-LeRoux/IguanaTex#54]
I have installed IguanaTex following the instructions on the M1 MacBook Pro (14-inch, 2021). AN ERROR WILL APPEAR when I click any button in the "Main Settings" window. The error message is 'Visual Basic for Applications: Run-time error "5" Invalid procedure call or argument'.
<img width="473" alt="1" src="https://github.com/Jonathan-LeRoux/IguanaTex/assets/12593541/44ca44b3-1c10-4419-9853-1474316daab0">
<img width="432" alt="2" src="https://github.com/Jonathan-LeRoux/IguanaTex/assets/12593541/688e20a8-eada-42f2-8ca6-4e2bfa50e43e">
How can I solve this problem?

**Comment by Jonathan-LeRoux** [comment]
Which installation did you use, manual or homebrew?
Maybe try the other one.
Can you use the New LaTeX display button?

**Comment by nmgzjf** [comment]
I have tried both methods, and the above situation will appear.
When I click the New LaTeX display button, the window will appear. However, when I click the Generate button, the error will appear.

**Comment by Jonathan-LeRoux** [comment]
What version of PowerPoint are you using?

If you could unload the addin and instead open the .pptm file and run the macros in its Iguanatex tab, then you may have the option to debug when the error occurs, which could help us pinpoint where things go wrong.

**Comment by Jonathan-LeRoux** [comment]
The error must been happening inside that function. Could you "step into" (F8) that function then keep "stepping over" (Shift+F8) until you hit the error? If the error happens at yet another function call, you'll need to "step into" again, etc., until you find the line that actually causes the problem.

**Comment by Jonathan-LeRoux** [comment]
I'm guessing your version of Powerpoint does not support SVG. 
- If you try to insert an SVG file in your presentation via the "Insert" tab in the ribbon (then "Pictures">"This device..." for example), does that succeed? 
- If it does, can you try to go to the "Graphics Format" tab and see if you have a "Convert to Shape" button in the ribbon? 

I need to better handle this. Could you try to modify the code as follows?
```
    Dim Sel As Selection
    inSh.Select
    On Error Resume Next
    Call CommandBars.ExecuteMso("SVGEdit")
    On Error GoTo 0 
    Set Sel = Application.ActiveWindow.Selection
    Dim NewShape As Shape
```
The code should run without error. The downside is that it will silently do nothing, leaving the SVG as a Graphics object (same as just inserting via the "Insert" menu) instead of converting it to a Shape object. Another option would be to display a message saying "Your Powerpoint version appears not to have full SVG support, the file will be inserted as a Graphics object without being converted to a Shape".

**Comment by Jonathan-LeRoux** [comment]
Could you try the .pptm file in [IguanaTex_v1_61_beta2.zip](https://github.com/Jonathan-LeRoux/IguanaTex/files/13663135/IguanaTex_v1_61_beta2.zip)? 

It should still insert the SVG but will display a box saying the object wasn't converted to Shape. If this works, I could add a "Never show this again" checkbox, so that the box no longer appears. I don't think IguanaTex adds much if anything over the simple "Insert SVG" feature of PowerPoint though.

**Comment by Jonathan-LeRoux** [comment]
Could you send me an example of SVG file that fails?

**Comment by williamdwarke** [comment]
Hi, I wanted to chime in that I'm getting this exact same error using PowerPoint 2016 on Windows 10 when I try to generate any LaTeX display. It appears to be some sort of issue with the SVG generation, since it shows up in every version of IguanaTex since 1.6. Strangely, the LaTeX display is still generated, but IguanaTex doesn't recognize it as a display so I can't interact with it after generating.

**Comment by Jonathan-LeRoux** [comment]
I had forgotten that this function also gets used when creating a Shape (formerly Vector) display, so that can create all sorts of problems.

I will do more tests and see if it is viable to leave SVG as an option for us on Office 2016. In the meantime, I recommend switching to EMF in the Main Settings.

**Comment by williamdwarke** [comment]
Hi Jonathan, I did end up switching back to EMF and it seems to be working now. Thanks for the input!

**Comment by Jonathan-LeRoux** [comment]
@AstanVizu I think you're hitting a separate issue reported in https://github.com/Jonathan-LeRoux/IguanaTex/issues/45 and https://github.com/Jonathan-LeRoux/IguanaTex/issues/22#issuecomment-972287547, due to the use of PDF as intermediate step for SVG conversion ("SVG via PDF w/ dvisvgm"). If you use "SVG via DVI w/ dvisvgm", things should be better.

I realized that the use of SVG files not converted to Shape is not ideal, however. Some parts of the display can be hidden, for example the bottom is cut in the bottom display below (top: SVG converted to Shape; bottom: no conversion):
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/14299374/8b0fd8c4-9fe7-434c-b738-f4b677b5548c)

So I'm not sure I should let users create such displays, as they may not realize that the displays are not perfect. One option is to include a clear warning in the message box. Another is to simply disable SVG conversion.

**Comment by Jonathan-LeRoux** [comment]
Closing this issue as it is now "fixed" (as in, "handled properly") in [Release v1.61](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.61).
