### ISSUE TITLE
Could not start pdflatex

### ISSUE THREAD

**Issue by MrSneeuwvlokje** [Jonathan-LeRoux/IguanaTex#59]
I have been using this add-in for a day and **it worked**. The next day I try it I keep getting the following error message:
![Knipsel](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/7eb79e1d-cdff-4ab4-8efe-817f4076ec85)

I am 100% sure the pdflatex.exe file is located in the folder "C:\Users\cve11\AppData\Local\Programs\MiKTeX\miktex\bin\x64".
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/9164a56c-101f-4c6c-a2db-c6eb4303b129)

 I have tried everything, reinstalling the add-in, reinstalling miktek, removing the filepath to the folder containing the latex executables so that it would just go to default, trying older versions of iguanatex. Nothing works!

If i go to cmd and type in pdflatex it has no problem executing it (as can be seen in the screenshot below)
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/789a909b-b05d-4a01-b8a8-aba302c3daf4)

I use the latest version of iguanatex (IguanaTex_v1_60_3)
powerpoint version: 2401
OS: windows 10

Are there more people running into this problem or know how to fix it? Thanks for your time

**Comment by Jonathan-LeRoux** [comment]
Could you try running again with the "Debug" box checked, then use the Copy button in the pop up window to copy the exact command that leads to an issue, open a CMD window, navigate to your temp folder (c:\temp, typically), and run it there? 
Let's first see what this gives.

Next, if you manually set the path to "C:\Users\cve11\AppData\Local\Programs\MiKTeX\miktex\bin\x64" in the Main Settings, please also try generating a display while leaving the path blank.

Finally, could you also try running "C:\Users\cve11\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex" (without ".exe.") inside the CMD window? That works fine on my end, but until v1.59 I used to add ".exe" on Windows, probably because I did notice some issue without it a long time ago. More recently, this was [brought up on the IguanaTex Google group](https://groups.google.com/g/iguanatex/c/lKnnG1aYxdQ/m/1GVOxZ6RCAAJ) as preventing the use of cygwin's LaTeX, and as I could no longer find the reason for adding ".exe", I removed it in v1.60. So I'm curious to see whether it could be needed in some cases, and if so what are these cases.

**Comment by MrSneeuwvlokje** [comment]
Hi Jonathan,
Thanks for your quick response.

with debug on i get this.
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/a29ebe86-26d4-408e-ab40-81afd105a96b)
the command is: "C:\Users\cve11\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex" -output-format dvi -shell-escape -interaction=batchmode IguanaTex_tmp.tex"
If  press continue i get this error:
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/daf6dfac-3882-4c73-b167-59bcf4d6a5df)

If i leave the path blank in the Main Settings I get a similar error
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/8c02583b-f578-4a2f-8687-8fa055cd28c7)
the command is: "pdflatex" -output-format dvi -shell-escape -interaction=batchmode IguanaTex_tmp.tex"
If  press continue i get this error:
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/c5c136a4-046c-464e-9a4a-1fe7f2ee9a0f)

If i run it in my temp folder it works fine (i think?). With or without path results in the same 
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/164509922/bf4d13b4-08bb-4e4f-8011-e9d02a26a674)

running "C:\Users\cve11\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex" (without ".exe.") in the command window also works fine.

**Comment by Jonathan-LeRoux** [comment]
Hmm, I'm wondering if maybe you are having permission issues similar to https://github.com/Jonathan-LeRoux/IguanaTex/issues/48. Now the question is why it worked the first day and no longer works. Maybe this triggered a warning to your IT department and your admin blocked Office from starting processes?

**Comment by MrSneeuwvlokje** [comment]
Yeah I saw that issue and i wondered the same. I do work on a laptop from the university so it could be the case. I will try and install iguanatex on my pc at home later today and see if it works there properly. If it works normally on my home pc for a couple of days in a row I'll let you know and close this issue.

Thanks for your time/help. It is appreciated. Iguanatex is a very nice tool!

**Comment by Jonathan-LeRoux** [comment]
I suggest you reach out to your university IT, they may be able to white-list IguanaTex, or tell you that they have nothing to do with the issue.

**Comment by MrSneeuwvlokje** [comment]
I got a response from the university that they indeed block all office applications from creating child processes. They might make an exception for me, so fingers crossed.

Thanks for your help.

**Comment by Jonathan-LeRoux** [comment]
Thanks for the update, fingers crossed indeed.
