### ISSUE TITLE
Support Tectonic TeX Engine

### ISSUE THREAD

**Issue by KagaJiankui** [Jonathan-LeRoux/IguanaTex#63]
[**Tectonic**](https://github.com/tectonic-typesetting/tectonic) is a modernized, complete, self-contained [TeX](https://en.wikipedia.org/wiki/TeX)/[LaTeX](https://www.latex-project.org/) engine, powered by [XeTeX](http://xetex.sourceforge.net/) and [TeXLive](https://www.tug.org/texlive/). This engine is light-weighted comparing to MiKTeX or TeXLive, and fast in compilation.

Since the tectonic TeX engine is well documentated by their develop team, is there any possibility for IguanaTeX to support the CLI of tectonic TeX engine?

**Comment by Jonathan-LeRoux** [comment]
Thanks for suggesting this, I hadn't heard about Tectonic. It does seem that Tectonic can indeed be integrated quite simply into IguanaTex. Here is [a beta v1.61.1 version](https://github.com/user-attachments/files/15537290/IguanaTex_v1_61_1.zip) which adds Tectonic as a new compilation engine. 

Thankfully, shell-escape was added to Tectonic, so that wasn't a problem, and I mainly add to refactor a bit and deal with options for XDV vs PDF.

Notes: 
- dvisvgm is still needed to convert to Shape, and GhostScript and (on Windows) ImageMagick are still needed to convert to Picture.
- if the user wants to specify a path to the LaTeX executables (or a prefix, as in https://github.com/Jonathan-LeRoux/IguanaTex/issues/64), then `tectonic` *needs* to be on that path.
- if no path is specified for the LaTeX executables, then `tectonic` *needs* to be on the user's PATH.
- (obviously) `latexmk` is disabled when using `tectonic`

**Comment by KagaJiankui** [comment]
Thanks for your blazing fast develop! I'll feedback for this beta ASAP.

**Comment by KagaJiankui** [comment]
The beta version works fine with my tectonic installation! Very nice work!

**Comment by Jonathan-LeRoux** [comment]
Thanks for the prompt feedback!
If someone on Mac can give this a quick spin as well, that would be great. Otherwise I'll wait until I can do some tests myself before making a release. Not that I expect any issue.

**Comment by Jonathan-LeRoux** [comment]
Fixed with [v1.62 release](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.62).
