### ISSUE TITLE
Allow for custom LaTeX command, not just folder

### ISSUE THREAD

**Issue by francescoboc** [Jonathan-LeRoux/IguanaTex#64]
Hi,
I would like to tell Iguanatex to use my LaTeX installation in WSL (Windows Subsystem for Linux), but I cannot find this option. There is the option to specify a custom folder for the LaTeX installation under Windows, but that is not what I need.

Basically, instead of calling the command `pdflatex`, I would like it to call `wsl -e pdflatex`. I am confident that this would work because I am already using this approach for Texstudio for Windows:

![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/33369475/2cfb69a0-43fa-4c7d-80fe-90521c1039b9)

Moreover, manually compiling the `IguanaTex_tmp.tex` with `wsl -e pdflatex -output-format dvi -shell-escape -interaction=batchmode`, which is the command called by Iguanatex preceeded by `wsl -e`, successfully produces the corresponding `dvi` file:

![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/33369475/09816ce4-00f5-4b88-b073-4e3a52703585)

Thank you very much.

**Comment by Jonathan-LeRoux** [comment]
I think simply commenting out [this line](https://github.com/Jonathan-LeRoux/IguanaTex/blob/38d7d26ac899e1557e29d21b5d74eff966f2e1c2/SetTempForm.frm#L138) which adds a trailing slash to the path specified in the settings may work for your case. You would then just have to write `wsl -e ` (with a trailing space) instead of a folder. I just tried and got the right string. Here is [a version with the change](https://github.com/user-attachments/files/15536630/IguanaTex_v1_61_1.zip).

Instead of that box being used to specify a folder, it's now used to specify more generally a "prefix". I simply warn the user that it's their responsibility to add a trailing slash or backslash (it's automatically fixed depending on the platform) if their prefix is a folder.

**Comment by francescoboc** [comment]
Thank you very much for the quick response! Unfortunately, this still throws an error:

![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/33369475/c5ddc36d-5804-46fb-a483-9d8139a24238)

I suspect that the problem might be in the quotes `"`, as if I try to manually re-run the command without them, it compiles:

![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/33369475/9b76d2d5-ff3a-49e0-b8df-8560bc591e77)

**Comment by Jonathan-LeRoux** [comment]
Argh, that would have been too easy. I'm trying to think about the best way to solve this. Maybe check if `wsl` is part of the string and if so just not add quotes...
 Do you expect to use WSL also for Ghostscript and/or ImageMagick?

**Comment by Jonathan-LeRoux** [comment]
Here is a version that checks if the prefix starts with `wsl ` and if so does not add quotes: [IguanaTex_v1_61_1.zip](https://github.com/user-attachments/files/15599002/IguanaTex_v1_61_1.zip)

**Comment by francescoboc** [comment]
> Here is a version that checks if the prefix starts with `wsl ` and if so does not add quotes: [IguanaTex_v1_61_1.zip](https://github.com/user-attachments/files/15599002/IguanaTex_v1_61_1.zip)

Thank you, this works like a charm! Even the `dvisvgm` command works!

> Do you expect to use WSL also for Ghostscript and/or ImageMagick?

Yes, possibly. But I'm ok just with the basic functionality that I have now.

One comment: are quotes necessary at all? Wouldn't the `pdflatex` command in Windows work without them?

**Comment by Jonathan-LeRoux** [comment]
Fixed with [v1.62 release](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.62).
