### ISSUE TITLE
Access to Settings as a Text File

### ISSUE THREAD

**Issue by RoyiAvital** [Jonathan-LeRoux/IguanaTex#71]
Is there a place where the settings are saved to as a text file?

I want to backup the current configuration yet I'm not sure where the settings are saved.

**Comment by Jonathan-LeRoux** [comment]
That's a good idea.

The settings are saved in the Registry on Windows under `Computer\HKEY_CURRENT_USER\Software\IguanaTex` (which you might be able to export), and... I'm not entirely sure where on Mac, maybe `/Library/Application Support/Microsoft/Office365/User Content.localized/Add-Ins.localized/`? I don't have a Mac now to check, sorry.

I'll look at implementing this. Fair warning, it may take quite a bit of time :)

**Comment by Jonathan-LeRoux** [comment]
In the meantime, I would just screenshot the Main Settings.

**Comment by RoyiAvital** [comment]
> In the meantime, I would just screenshot the Main Settings.
This is what I do :-).

> `Computer\HKEY_CURRENT_USER\Software\IguanaTex`
That's a great pointer.

It would be great to either export / import the settings or just have them in text format somewhere so they can be edited manually or just be copied.

**Comment by Jonathan-LeRoux** [comment]
I finally got around to implementing this. I will soon make a v1.62 release, but in the meantime, feel free to give this a try: [IguanaTex_v1_62_12012024.zip](https://github.com/user-attachments/files/17970168/IguanaTex_v1_62_12012024.zip).
There is now an option to export/import the settings to/from an XML file. Note that this doesn't just load the settings into the settings window for the user to confirm, it actually overwrites any settings in the registry. This is necessary because there are IguanaTex settings that are set elsewhere (the main IguanaTex window, including templates, and the window to load vector graphics files). Instead of blindly saving/overwriting the whole registry folder, I'm only saving or reading the settings that IguanaTex knows about. 
Hopefully, I got this right and it won't mess up anything.

**Comment by RoyiAvital** [comment]
Wonderful.

I will give it a try and report issues if I encounter them.

**Comment by Jonathan-LeRoux** [comment]
Fixed with [v1.62 release](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.62).

**Comment by RoyiAvital** [comment]
By the way, why not enable Discussions in this repository instead of Google Groups?
