### ISSUE TITLE
After "write to file failed", return to editor

### ISSUE THREAD

**Issue by koppor** [Jonathan-LeRoux/IguanaTex#77]
I use `lualatex` in the stop mode to see the first error. I forgot to close the lualatex interpreter. Then I pressed "ReGenerate". Following window appears:

![image](https://github.com/user-attachments/assets/f53752a0-bafd-4cbe-b56e-5b3f3aa7c0b5)

I press "End"

Now, "IguanaTex" popup is closed. Moreover, it contains the data **before** the last edit - not before the last clickon "ReGenerate". 

I could recover my data by using the contents of `IguanaTex_tmp.tex`. But I would prefer if IguanaTex would just return to the edit window (instead of closing it) after a file write error.

**Comment by Jonathan-LeRoux** [comment]
Could you give more details about how you got there?

Also, what is "it" in "it contains the data before the last edit"?

**Comment by koppor** [comment]
Sure.

1.  Create LaTeX display with wrong latex command\
    ![image](https://github.com/user-attachments/assets/c5ed3ac4-699d-4bc9-bf10-5aa4076d2819)
2. Click "Generate"
3. See "Error in LaTeX" code\
    ![image](https://github.com/user-attachments/assets/ff92d8ec-adf5-4cb5-8bf6-005d260c0117)
4. Click "Close"
4. Open cmd.exe
5. Type `cd \TEMP\IguanaTeX` <kbd>Enter</kbd>
6. Type `lualatex IguanaTex_temp.tex` <kbd>Enter</kbd>\
    ![image](https://github.com/user-attachments/assets/90de3244-072f-4154-82b7-a97cb400e0d3)
7. Switch back to PowerPoint
8. Click "Generate"\
    ![image](https://github.com/user-attachments/assets/bd948618-49e3-4aba-9c53-3e7426dec8e5)
9. Click "End"
10. See that "valid latex" is shwon

Expected behavior:

![image](https://github.com/user-attachments/assets/d5cc31e3-c2ac-44b6-954b-f38d6eb387ed)

By "it", I mean the Window titled "IguanaTex" is opened and the contents are the ones before clicking on "Regenerate"

---

Settings:

![image](https://github.com/user-attachments/assets/bc38d5c7-c8e2-4cdf-aca2-67dd310a3562)

---

**Comment by Jonathan-LeRoux** [comment]
I assume you are first creating a display successfully with some code (otherwise you would get "Generate", not "ReGenerate") and also between steps 8 and 9, you fix the LaTeX to `\wrongLatex`.

Clicking "End" will indeed end everything, and because IguanaTex couldn't write to `IguanaTex_tmp.tex` (which is why you got an error), then indeed the content is lost. I think the right way to handle this would be to test that the file is writable, and display a message if that isn't the case, to avoid raising an error in the first place. I think it's kind of a corner case scenario that this file would not be writable, but it doesn't hurt to test, so I'll add this to my To Do list.

**Comment by koppor** [comment]
Tested with the version provided at https://github.com/Jonathan-LeRoux/IguanaTex/issues/76#issuecomment-2453459300. Works. Thank you for the quick reaction!
